# Generated by Django 5.2.7 on 2025-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('idem_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('qr', 'qr')], max_length=10)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='pending', max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('retries', models.IntegerField(default=0)),
                ('conn_mode_snapshot', models.CharField(default='mock', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
